apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
  namespace: kafka-db-ms-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      name: gateway-service
      labels:
        app: gateway-service
    spec:
      initContainers:
        - name: check-configserver-ready
          image: busybox
          command: ['/bin/sh']
          args: ['-c', 'until nc -z microservices-config-service 8180; do echo waiting for microservices-config-sever ready; sleep 5; done;']
      containers:
        - name: gateway-service
          image: placidenduwayo1/gateway-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
              name: gateway-port
          readinessProbe:
            httpGet:
              port: gateway-port
              path: /
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: gateway-port
              path: /
            initialDelaySeconds: 15
            periodSeconds: 10
          startupProbe:
            httpGet:
              port: gateway-port
              path: /
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service
  namespace: kafka-db-ms-ns
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
      nodePort: 30181
  type: NodePort
  