apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-config-service
  labels:
    app: microservices-config-service
  namespace: kafka-db-ms-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices-config-service
  template:
    metadata:
      name: microservices-config-service
      labels:
        app: microservices-config-service
    spec:
      containers:
        - name: microservices-config-service
          image: placidenduwayo1/microservices-config-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8180
              name: conf-svc-port
              hostPort: 8180
          readinessProbe:
            tcpSocket:
              port: conf-svc-port
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: conf-svc-port
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            tcpSocket:
              port: conf-svc-port
            failureThreshold: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: microservices-config-service
  labels:
    app: microservices-config-service
  namespace: kafka-db-ms-ns
spec:
  selector:
    app: microservices-config-service
  ports:
    - protocol: TCP
      port: 8180
      targetPort: 8180
      nodePort: 30180
  type: NodePort
      