version: '3.4'
services:
  
  mysql-ms-dbs:
    image: mysql:8.0
    container_name: mysql-ms-dbs
    restart: always
    ports:
      - "3307:3306"
    networks:
      - kafka-network
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - persistence-dbs:/var/lib/mysql

  zookeeper:
    image: zookeeper:3.4.9
    container_name: zookeeper
    hostname: zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      - kafka-network
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  kafka-broker-1:
    image: obsidiandynamics/kafka
    container_name: kafka-broker-1
    networks:
      - kafka-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:19092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka-broker-1:19092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  kafka-broker-2:
    image: obsidiandynamics/kafka
    container_name: kafka-broker-2
    networks:
      - kafka-network
    ports:
      - "9093:9093"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka-broker-2:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: nc -z localhost 9093 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  kafka-broker-3:
    image: obsidiandynamics/kafka
    container_name: kafka-broker-3
    networks:
      - kafka-network
    ports:
      - "9094:9094"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:39092,DOCKER_EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka-broker-3:39092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: nc -z localhost 9094 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  schema-registry:
    image: confluentinc/cp-schema-registry:5.4.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-broker-1:19092,kafka-broker-2:29092,kafka-broker-3:39092
    networks:
      - kafka-network
  

  kafdrop-UI:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop-UI
    restart: "no"
    ports:
      - "9001:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka-broker-1:19092,kafka-broker-2:29092,kafka-broker-3:39092
    depends_on:
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
    networks:
      - kafka-network

  # spring boot utility microservices
  microservices-config-service:
    image: placidenduwayo1/microservices-config-service:latest
    container_name: microservices-config-service
    build:
      context: ./Utility-Services/microservices-config-service
      dockerfile: Dockerfile
    ports:
      - "8180:8180"
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://microservices-config-service:8180" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - kafka-network

  microservices-registry-service:
    image: placidenduwayo1/microservices-registry-service:latest
    container_name: microservices-registry-service
    build:
      context: ./Utility-Services/microservices-registry-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - kafka-network
    depends_on:
      microservices-config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://microservices-registry-service:8761" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  # gateway microservice
  gateway-service:
    image: placidenduwayo1/gateway-service:latest
    container_name: gateway-service
    build:
      context: ./Utility-Services/gateway-service
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    networks:
      - kafka-network
    depends_on:
      microservices-registry-service:
        condition: service_healthy
        
networks:
  kafka-network:
volumes:
  persistence-dbs: