apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-3
  labels:
    app: kafka-broker-3
  namespace: kafka-db-ms-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-3
  template:
    metadata:
      name: kafka-broker-3
      labels:
        app: kafka-broker-3
    spec:
      initContainers:
        - name: check-zookeeper-ready
          image: busybox
          command: [ '/bin/sh' ]
          args: [ '-c', 'until nc -z zookeeper 2181; do echo waiting for zookeeper service ready; sleep 5; done;']
      hostname: kafka-broker-3
      containers:
        - name: kafka-broker-3
          image: obsidiandynamics/kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9094
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  key: kafka_broker_id_2
                  name: kafka-infra-env-variables-cm
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  key: kafka_listeners_security_protocol
                  name: kafka-infra-env-variables-cm
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  key: zookeeper_connect
                  name: kafka-infra-env-variables-cm
            - name: KAFKA_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: kafka_listeners_3
                  name: kafka-infra-env-variables-cm
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: kafka_advertised_listeners_3
                  name: kafka-infra-env-variables-cm
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-3
  labels:
    app: kafka-broker-3
  namespace: kafka-db-ms-ns
spec:
  selector:
    app: kafka-broker-3
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094
      nodePort: 30094
      name: 9094-9094
  type: NodePort