apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop-ui
  labels:
    app: kafdrop-ui
  namespace: kafka-db-ms-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop-ui
  template:
    metadata:
      name: kafdrop-ui
      labels:
        app: kafdrop-ui
    spec:
      initContainers:
        - name: check-kafka-broker-1-ready
          image: busybox
          command: [ '/bin/sh' ]
          args: [ '-c','until nc -z kafka-broker-1 9092; do echo waiting for kafka-broker-1 ready; sleep 5; done;' ]
        - name: check-kafka-broker-2-ready
          image: busybox
          command: [ '/bin/sh' ]
          args: [ '-c', 'until nc -z kafka-broker-2 9093; do echo waiting for kafka-broker-2 ready; sleep 5; done;' ]
        - name: check-kafka-broker-3-ready
          image: busybox
          command: [ '/bin/sh' ]
          args: [ '-c', 'until nc -z kafka-broker-3 9094; do echo waiting for kafka-broker-3 ready; sleep 5; done;' ]
      containers:
        - name: kafdrop-ui
          image: obsidiandynamics/kafdrop
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              name: kafdrop-port
          env:
            - name: KAFKA_BROKERCONNECT
              valueFrom:
                configMapKeyRef:
                  name: kafka-infra-env-variables-cm
                  key: kafka_bootstrap_servers
          readinessProbe:
            tcpSocket:
              port: kafdrop-port
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: kafdrop-port
            initialDelaySeconds: 15
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: kafdrop-port
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop-ui
  labels:
    app: kafdrop-ui
  namespace: kafka-db-ms-ns
spec:
  selector:
    app: kafdrop-ui
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: 9000-9000
      nodePort: 30000
  type: NodePort