apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-1
  labels:
    app: kafka-broker-1
  namespace: kafka-db-ms-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-1
  template:
    metadata:
      name: kafka-broker-1
      labels:
        app: kafka-broker-1
    spec:
      initContainers:
        - name: check-zookeeper-ready
          image: busybox
          command: ['/bin/sh']
          args: ['-c', 'until nc -z zookeeper 2181; do echo waiting for zookeeper service ready; sleep 5; done;']
      hostname: kafka-broker-1
      containers:
        - name: kafka-broker-1
          image: obsidiandynamics/kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
              name: broker1-port
              hostPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  key: kafka_broker_id_0
                  name: kafka-infra-env-variables-cm
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  key: kafka_listeners_security_protocol
                  name: kafka-infra-env-variables-cm
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  key: zookeeper_connect
                  name: kafka-infra-env-variables-cm
            - name: KAFKA_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: kafka_listeners_1
                  name: kafka-infra-env-variables-cm
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: kafka_advertised_listeners_1
                  name: kafka-infra-env-variables-cm
          readinessProbe:
            tcpSocket:
              port: broker1-port
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: broker1-port
            initialDelaySeconds: 15
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: broker1-port
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1
  labels:
    app: kafka-broker-1
  namespace: kafka-db-ms-ns
spec:
  selector:
    app: kafka-broker-1
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30092
      name: 9092-9092
  type: NodePort