apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-kafka-avro-aepc-bs-ms-project
  labels:
    app: k8s-kafka-avro-aepc-bs-ms-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-kafka-avro-aepc-bs-ms-project
  template:
    metadata:
      name: k8s-kafka-avro-aepc-bs-ms-project
      labels:
        app: k8s-kafka-avro-aepc-bs-ms-project
    spec:
      containers:
        - name: k8s-kafka-avro-aepc-bs-ms-project
          image: placidenduwayo1/k8s-kafka-avro-aepc-bs-ms-project
          imagePullPolicy: Always
          ports:
            - containerPort: 8584
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-broker-1:9092,kafka-broker-2:9093,kafka-broker-3:9094
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-kafka-avro-aepc-bs-ms-project
  labels:
    app: k8s-kafka-avro-aepc-bs-ms-project
spec:
  selector:
    app: k8s-kafka-avro-aepc-bs-ms-project
  ports:
    - protocol: TCP
      port: 8584
      targetPort: 8584
      name: 8584-8584
  type: LoadBalancer
      