apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-kafka-avro-aepc-bs-ms-company
  labels:
    app: k8s-kafka-avro-aepc-bs-ms-company
  namespace: microservices-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-kafka-avro-aepc-bs-ms-company
  template:
    metadata:
      name: k8s-kafka-avro-aepc-bs-ms-company
      labels:
        app: k8s-kafka-avro-aepc-bs-ms-company
    spec:
      containers:
        - name: k8s-kafka-avro-aepc-bs-ms-company
          image: placidenduwayo1/k8s-kafka-avro-aepc-bs-ms-company
          imagePullPolicy: Always
          ports:
            - containerPort: 8583
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: env-variables-cm
                  key: kafka_bootstrap_servers
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-kafka-avro-aepc-bs-ms-company
  labels:
    app: k8s-kafka-avro-aepc-bs-ms-company
  namespace: microservices-ns
spec:
  selector:
    app: k8s-kafka-avro-aepc-bs-ms-company
  ports:
    - protocol: TCP
      port: 8583
      targetPort: 8583
      name: 8583-8583
      nodePort: 30583
  type: LoadBalancer