apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-kafka-avro-aepc-bs-ms-employee
  labels:
    app: k8s-kafka-avro-aepc-bs-ms-employee
  namespace: kafka-db-ms-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-kafka-avro-aepc-bs-ms-employee
  template:
    metadata:
      name: k8s-kafka-avro-aepc-bs-ms-employee
      labels:
        app: k8s-kafka-avro-aepc-bs-ms-employee
    spec:
      containers:
        - name: k8s-kafka-avro-aepc-bs-ms-employee
          image: placidenduwayo1/k8s-kafka-avro-aepc-bs-ms-employee
          imagePullPolicy: Always
          ports:
            - containerPort: 8582
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-infra-env-variables-cm
                  key: kafka_bootstrap_servers
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-kafka-avro-aepc-bs-ms-employee
  labels:
    app: k8s-kafka-avro-aepc-bs-ms-employee
  namespace: kafka-db-ms-ns
spec:
  selector:
    app: k8s-kafka-avro-aepc-bs-ms-employee
  ports:
    - protocol: TCP
      port: 8582
      targetPort: 8582
      name: 8582-8582
      nodePort: 30582
  type: LoadBalancer