apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-kafka-avro-aepc-bs-ms-address
  labels:
    app: k8s-kafka-avro-aepc-bs-ms-address
  namespace: kafka-db-ms-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-kafka-avro-aepc-bs-ms-address
  template:
    metadata:
      name: k8s-kafka-avro-aepc-bs-ms-address
      labels:
        app: k8s-kafka-avro-aepc-bs-ms-address
    spec:
      containers:
        - name: k8s-kafka-avro-aepc-bs-ms-address
          image: placidenduwayo1/k8s-kafka-avro-aepc-bs-ms-address:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8581
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-infra-env-variables-cm
                  key: kafka_bootstrap_servers
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-kafka-avro-aepc-bs-ms-address
  labels:
    app: k8s-kafka-avro-aepc-bs-ms-address
  namespace: kafka-db-ms-ns
spec:
  selector:
    app: k8s-kafka-avro-aepc-bs-ms-address
  ports:
    - protocol: TCP
      port: 8581
      targetPort: 8581
      nodePort: 30581
  type: LoadBalancer
      