apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-kafka-avro-aepc-bs-ms-project
  labels:
    app: k8s-kafka-avro-aepc-bs-ms-project
  namespace: kafka-db-ms-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-kafka-avro-aepc-bs-ms-project
  template:
    metadata:
      name: k8s-kafka-avro-aepc-bs-ms-project
      labels:
        app: k8s-kafka-avro-aepc-bs-ms-project
    spec:
      initContainers:
        - name: check-configserver-ready
          image: busybox
          command: [ '/bin/sh' ]
          args: [ '-c', 'until nc -z microservices-config-service 8180; do echo waiting for ms config server; sleep 5; done;' ]
        - name: check-db-ready
          image: busybox
          command:
            - '/bin/sh'
          args:
            - '-c'
            - 'until nc -z mysql-ms-dbs 3306; do echo waiting database service ready; sleep 5; done;'
        - name: check-kafka-broker1-ready
          image: busybox
          command:
            - '/bin/sh'
          args:
            - '-c'
            - 'until nc -z kafka-broker-1 9092; do echo waiting for kafka broker1 ready; sleep 5; done;'
        - name: check-kafka-broker2-ready
          image: busybox
          command:
            - '/bin/sh'
          args:
            - '-c'
            - 'until nc -z kafka-broker-2 9093; do echo waiting for kafka broker2 ready; sleep 5; done;'
        - name: check-kafka-broker3-ready
          image: busybox
          command:
            - '/bin/sh'
          args:
            - '-c'
            - 'until nc -z kafka-broker-3 9094; do echo waiting for kafka broker3 ready; sleep 5; done;'
      containers:
        - name: k8s-kafka-avro-aepc-bs-ms-project
          image: placidenduwayo1/k8s-kafka-avro-aepc-bs-ms-project
          imagePullPolicy: Always
          ports:
            - containerPort: 8584
              name: project-port
              hostPort: 8584
          readinessProbe:
            httpGet:
              port: project-port
              path: /
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: project-port
              path: /
            initialDelaySeconds: 15
            periodSeconds: 10
          startupProbe:
            httpGet:
              port: project-port
              path: /
            failureThreshold: 30
            periodSeconds: 10
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-infra-env-variables-cm
                  key: kafka_bootstrap_servers
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-kafka-avro-aepc-bs-ms-project
  labels:
    app: k8s-kafka-avro-aepc-bs-ms-project
  namespace: kafka-db-ms-ns
spec:
  selector:
    app: k8s-kafka-avro-aepc-bs-ms-project
  ports:
    - protocol: TCP
      port: 8584
      targetPort: 8584
      name: 8584-8584
      nodePort: 30584
  type: LoadBalancer
      