apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-kafka-avro-aepc-bs-ms-address
  labels:
    app: k8s-kafka-avro-aepc-bs-ms-address
  namespace: kafka-db-ms-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-kafka-avro-aepc-bs-ms-address
  template:
    metadata:
      name: k8s-kafka-avro-aepc-bs-ms-address
      labels:
        app: k8s-kafka-avro-aepc-bs-ms-address
    spec:
      initContainers:
        - name: check-configserver-ready
          image: busybox
          command: [ '/bin/sh' ]
          args: [ '-c', 'until nc -z microservices-config-service 8180; do echo waiting for ms config server; sleep 5; done;' ]
        - name: check-db-ready
          image: busybox
          command:
            - '/bin/sh'
          args:
            - '-c'
            - 'until nc -z mysql-ms-dbs 3306; do echo waiting database service ready; sleep 5; done;'
        - name: check-kafka-broker1-ready
          image: busybox
          command:
            - '/bin/sh'
          args:
            - '-c'
            - 'until nc -z kafka-broker-1 9092; do echo waiting for kafka broker1 ready; sleep 5; done;'
        - name: check-kafka-broker2-ready
          image: busybox
          command:
            - '/bin/sh'
          args:
            - '-c'
            - 'until nc -z kafka-broker-2 9093; do echo waiting for kafka broker2 ready; sleep 5; done;'
        - name: check-kafka-broker3-ready
          image: busybox
          command:
            - '/bin/sh'
          args:
            - '-c'
            - 'until nc -z kafka-broker-3 9094; do echo waiting for kafka broker3 ready; sleep 5; done;'
      containers:
        - name: k8s-kafka-avro-aepc-bs-ms-address
          image: placidenduwayo1/k8s-kafka-avro-aepc-bs-ms-address:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8581
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-infra-env-variables-cm
                  key: kafka_bootstrap_servers
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-kafka-avro-aepc-bs-ms-address
  labels:
    app: k8s-kafka-avro-aepc-bs-ms-address
  namespace: kafka-db-ms-ns
spec:
  selector:
    app: k8s-kafka-avro-aepc-bs-ms-address
  ports:
    - protocol: TCP
      port: 8581
      targetPort: 8581
      nodePort: 30581
  type: LoadBalancer
      