apiVersion: apps/v1
kind: Deployment
metadata:
  name: avro-schema-registry
  labels:
    app: avro-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avro-schema-registry
  template:
    metadata:
      name: avro-schema-registry
      labels:
        app: avro-schema-registry
    spec:
      containers:
        - name: avro-schema-registry
          image: confluentinc/cp-schema-registry:5.4.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka-broker-1:9092,PLAINTEXT://kafka-broker-1:9093,PLAINTEXT://kafka-broker-1:9094
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: avro-schema-registry
  labels:
    app: avro-schema-registry
spec:
  selector:
    app: avro-schema-registry
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
      