apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-1
  labels:
    app: kafka-broker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-1
  template:
    metadata:
      name: kafka-broker-1
      labels:
        app: kafka-broker-1
    spec:
      hostname: kafka-broker-1
      containers:
        - name: kafka-broker-1
          image: obsidiandynamics/kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: '0'
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 'zookeeper:2181'
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092,PLAINTEXT_HOST://0.0.0.0:19092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-broker-1:9092,PLAINTEXT_HOST://localhost:19092

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1
  labels:
    app: kafka-broker-1
spec:
  selector:
    app: kafka-broker-1
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: LoadBalancer