apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-3
  labels:
    app: kafka-broker-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-3
  template:
    metadata:
      name: kafka-broker-3
      labels:
        app: kafka-broker-3
    spec:
      hostname: kafka-broker-3
      containers:
        - name: kafka-broker-3
          image: obsidiandynamics/kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9094
          env:
            - name: KAFKA_BROKER_ID
              value: '2'
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 'zookeeper:2181'
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9094,PLAINTEXT_HOST://0.0.0.0:39092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-broker-1:9094,PLAINTEXT_HOST://localhost:39092

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-3
  labels:
    app: kafka-broker-3
spec:
  selector:
    app: kafka-broker-3
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094
  type: LoadBalancer